### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by kenbloch** [Dan-in-CA/OSPi#104]
I updated OSPI this afternoon to version 2.2.46 and now having issues. 

First is that when I try to edit programs I get a message :internal server error" I have deleted programs  and can't create any new etc. I can run "Run Once" programs and verified that they are working. 

And I have tried doing restart and reboot but neither helped. I also purged the OSPi program and deleted the OSPi directory and reinstalled. It did not help either.

**Comment by Dan-in-CA** [comment]
There were a couple of contributed  updates yesterday. 
The modify.html file in the templates directory was missing a '}' character at column 55, line 284.
The problem with adding programs should be fixed.

I am not seeing the problem with the clock at this time although I did see it briefly just after the update but it cleared on a page refresh.

Update to the latest rev and things should be working.

**Comment by kenbloch** [comment]
Dan,

That fixed it you can close and delete the issue.

**Comment by Dan-in-CA** [comment]
Done. 
Thanks for reporting the problem on GitHub.
