### ISSUE TITLE
Run Program Manually When Disabled

### ISSUE THREAD

**Issue by Tails86** [Dan-in-CA/OSPi#107]
I find it somewhat confusing that the "RUN NOW" button under the programs tab in the web view essentially does nothing when the program is disabled. I see under run_now(), the programs page is brought up if the selected program is disabled. 

    if not p[0]:  # if program is disabled
        raise web.seeother('/vp')

Is there is a reason to do that? Personally, I think that there are some that may want to only run programs manually. At the very least, the "RUN NOW" button should be grayed out on a disabled program in the programs page.

**Comment by Dan-in-CA** [comment]
Agreed that it would be useful to be able to run disabled programs manually (or from a plugin).
I will modify the code.

**Comment by Dan-in-CA** [comment]
I commented out the code that would not allow a disabled program to "run now". The update is in the repo.

**Comment by Tails86** [comment]
Thank you
