### ISSUE TITLE
Couple spelling errors

### ISSUE THREAD

**Issue by jking1224** [Dan-in-CA/OSPi#109]
i18n\en_US\LC_MESSAGES\ospi_messages.po
  line: 358  should be: Access Plugins
  two "s"

i18n\en_US\LC_MESSAGES\ospi_messages.po
  line: 603  should be: Range address
  two "d"

i18n\en_US\LC_MESSAGES\ospi_messages.po
  line: 945  extra space

By the way, Dan, I think this project is great. I thank you for your continued work on this. If I ever figure out how to do git / github I will contribute code and help.

**Comment by Dan-in-CA** [comment]
Thanks for catching those. 
The text strings in i18n come from other files in the project as listed just above the strings. 2 of the changes were in plugins which are now in a separate repository.
