### ISSUE TITLE
Use a symbolic link for sip.py

### ISSUE THREAD

**Issue by ndesimone** [Dan-in-CA/OSPi#114]
I think the instructions are right on the money suggesting that users use the init.d mechanism for starting and stopping OSPi (SIP).  I would suggest that users use a symbolic link rather than moving a copy of sip.py to /etc/init.d.  That way, if improvements are released to sip.py, users will get to take advantage of them right away (especially if they use the upgrade plugin to keep their install fresh).  

I would also suggest putting the "Recommended Method" above the "Detailed Instructions", or maybe moving the "Detailed Instructions" to a "How to Develop" page.  I don't want to make it harder for developers, just easier for the folks that just want to download and get their lawns watered.

I'd make the changes myself, but I'm not sure of the moderation policy/process.  Hope this helps.

**Comment by Dan-in-CA** [comment]
I was just looking at the instructions and agree that putting the recommended method first would be best. I will make the change.

**Comment by ndesimone** [comment]
Hey Dan, what did you think about using a sym-link rather than a copy?
