### ISSUE TITLE
Rain delay countdown doesn't update display

### ISSUE THREAD

**Issue by sbrown4** [Dan-in-CA/OSPi#54]
It looks like this change in templates/home.html broke the screen update.
```
256                         var remaining = timerValue - devt; //Date.now(); // DK change

```
Now devt only gets updated when the page is refreshed. The problem with Date.now is that it is in UTC and the rain delay stop time is local time.  I'm not much of a javascript hacker, but here is an attempt at fixing it. This will break if the browser is in a different time zone than the controller. Maybe the stop time should be maintained in UTC or the controller time zone offset passed to the browser.

If you have a preferred approach to fixing this, let me know and I'll try to cook up a patch.

Steve
```
--- a/templates/home.html
+++ b/templates/home.html
@@ -250,9 +254,12 @@ $code:
                });
 
                function countdownTimer(timerId) {
+                       var time_now = new Date();
+                       var offset = time_now.getTimezoneOffset(); // in minutes
+                       var time_local = time_now.setMinutes(time_now.getMinutes() - offset); // adjust to local time
                        var timerElement = jQuery("#" + timerId);
                        var timerValue = parseFloat(timerElement.attr("data"));
-                       var remaining = timerValue - devt; //Date.now(); // DK change
+                       var remaining = timerValue - time_local;
                        var rHours = Math.floor(remaining/3600000);
                        var rMinutes = Math.floor((remaining%3600000)/60000);
                        if (rHours <=0 && rMinutes <=0) {
```

**Comment by Dan-in-CA** [comment]
In the 2.2.x version released on Jan. 9 2015 the controller timezone offset is passed to the browser. The main reason is to show the controller's local time even if the UI is being accessed from another time zone.
