### ISSUE TITLE
Relative path for email plugin

### ISSUE THREAD

**Issue by hslewis** [Dan-in-CA/OSPi#82]
When the email plugin attempts to open the log to email it assumes an absolute path so fails if ospi is not installed there. Consider making this path relative.

>>>>            

self.try_mail(subject, body, "/home/pi/ospi/data/log.json")

>>>

**Comment by Dan-in-CA** [comment]
Cleaning up old open issues. The plugins have been moved to:
https://github.com/Dan-in-CA/ospi_plugins
