### ISSUE TITLE
Issue with setting up 2 units on LAN

### ISSUE THREAD

**Issue by cphgsales** [Dan-in-CA/OSPi#83]
I set up one Opensprinkler pi and when I set up the second I get this error when I try and run the sudo python ospi.py 

plugins loaded:
  mobile_app
  monthly_adj
  relay
  signaling_example
  weather_adj
  weather_level_adj
Starting timing loop

http://0.0.0.0:8080/
Traceback (most recent call last):
  File "ospi.py", line 189, in <module>
    app.run()
  File "ospi.py", line 152, in run
    return web.httpserver.runsimple(func, ('0.0.0.0', port))
  File "/home/pi/OSPi/web/httpserver.py", line 157, in runsimple
    server.start()
  File "/home/pi/OSPi/web/wsgiserver/__init__.py", line 1753, in start
    raise socket.error(msg)
socket.error: No socket could be created

**Comment by Dan-in-CA** [comment]
Looks like you need to use a different port number for the second Pi. You can set the port number on the Options page

**Comment by cphgsales** [comment]
Where is the options page located?

**Comment by cphgsales** [comment]
Where is the options page located?

On Fri, Jan 16, 2015 at 12:56 AM, Dan <notifications@github.com> wrote:

> Looks like you need to use a different port number for the second Pi. You
> can set the port number on the Options page
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dan-in-CA/OSPi/issues/83#issuecomment-70191737>.
>



-- 
PETE VANELLO
Crystal Properties and Investments Inc
Corporate Broker
Phone (424) 260-7113
Fax  (702) 947-5769

*Email cphgsales@gmail.com <cphgsales@gmail.com>*

**Comment by Dan-in-CA** [comment]
It can be accessed from the menu buttons at the top of the web interface pages. If you have one unit running you can change the port of that one.

**Comment by Dan-in-CA** [comment]
Has this issue been resolved?

**Comment by cphgsales** [comment]
Yes it has thank You.

On Sun, Feb 1, 2015 at 12:04 PM, Dan <notifications@github.com> wrote:

> Has this issue been resolved?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dan-in-CA/OSPi/issues/83#issuecomment-72381375>.
>



-- 
PETE VANELLO
Crystal Properties and Investments Inc
Corporate Broker
Phone (424) 260-7113
Fax  (702) 947-5769

*Email cphgsales@gmail.com <cphgsales@gmail.com>*
