### ISSUE TITLE
Provide a way to config the baseurl, and allow https proxied.

### ISSUE THREAD

**Issue by mikedevita** [Dan-in-CA/OSPi#84]
I run nginx at home to proxy all of my web traffic, and drop an ssl in front of everything. 

if you drop an SSL nginx reverse proxy infront of OSPi two defects occur.

1. you are redirected to the `http://<hostname>/login` instead of `https://<hostname>/login`
2. some/most of the static assets are loaded via `http://`, when really they should be loaded with `//`, this will allow them to be loaded for both https and http.

## Steps to reproduce
1. put an nginx reverse proxy in front of the OSPi interface.
2. visit the "home" url, it will redirect to `http://<hostname>/login`
3. force that URL to be `https://<hostname>/login` and none of the static assets will load.

I would be happy to fork, and attempt to fix these two things and issue a PR.

**Comment by Dan-in-CA** [comment]
that would be great! 
Appreciate the input.

**Comment by mikedevita** [comment]
I'm not certain how webpy determines the baseurl to be honest. I got the assets issue fixed already.

**Comment by Dan-in-CA** [comment]
Check out:
http://webpy.org/cookbook/ctx

**Comment by mikedevita** [comment]
I am making this into a PR instead of an issue. You can delete it if needed.
