### ISSUE TITLE
Log Error

### ISSUE THREAD

**Issue by salbahra** [Dan-in-CA/OSPi#87]
I am noticing some lines in the log.json file end up with quote escaped format and some without the escape. This inconsistency is causing the mobile_app.py plugin to break and return no log data.

Any idea why this might be occurring?

Please see the forum for more detail and user description of error: https://opensprinkler.com/forums/topic/log-display/

**Comment by Dan-in-CA** [comment]
Hi Samer,

I noticed that but it hadn't caused a problem on My end so I was a bit 
slow in fixing it.
I'll try to take care of it today.

Dan

**Comment by Dan-in-CA** [comment]
OK. I think it is fixed now.

**Comment by salbahra** [comment]
Thank you!
