### ISSUE TITLE
missing gmt offset

### ISSUE THREAD

**Issue by dkebler** [Dan-in-CA/OSPi#94]
Just pulled the latest version: 2.2.30 (2015-02-21) and the field for setting the gmt offset is gone.  Now time reads gmt instead of what I had set.

I can set the time from ssh but I am assuming most will need to set it from web interface.

**Comment by Dan-in-CA** [comment]
Several IT pros suggested removing that setting. Once the timezone setting in raspi-settings is correct, the time shown in the UI should be correct.

**Comment by dkebler** [comment]
not a problem for me.  That's what I did.

But for noobs maybe a problem because now you are making them ssh and run
something from the commandline where before they did not have to ssh to the
pi.   Well maybe noobs are buying the full device in which I assume the web
interface deals with setting time zone.   Alternatively could have a bash
script fired from web interface that sets the timezone instead of using an
offset.  So then..just my, not an IT pro, perspective -:).  You can close
this.

On Wed, Feb 25, 2015 at 8:17 AM, Dan <notifications@github.com> wrote:

> Several IT pros suggested removing that setting. Once the timezone setting
> in raspi-settings is correct, the time shown in the UI should be correct.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dan-in-CA/OSPi/issues/94#issuecomment-75990248>.
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by Dan-in-CA** [comment]
I agree that there should be an easy way for users to do the OS level setup.
At least some detailed instructions in the new help system. I'll work on that for starters.
Thanks for the input.
